/**
 * Icon adapter — all components import icons from here.
 * To swap icon library, rewrite this file only.
 */
export {
  IconAlertTriangle,
  IconArrowBackUp,
  IconBinaryTree2,
  IconCalendar,
  IconCalendarEvent,
  IconCheck,
  IconCheckbox,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconCopy,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconFilter,
  IconFlame,
  IconFolder,
  IconGripVertical,
  IconHash,
  IconInbox,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLink,
  IconList,
  IconLogout,
  IconMinus,
  IconPlus,
  IconRefresh,
  IconRepeat,
  IconSearch,
  IconSettings,
  IconStar,
  IconTable,
  IconTag,
  IconTrash,
  IconTrophy,
  IconX,
} from '@tabler/icons-react';
